language: java
jdk: oraclejdk8
sudo: required
services:
  - docker
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
cache:
  directories:
    - $HOME/.m2
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: IsupcoJOsr112k4UYiD6wqbDZ/Sft9PuhQYFbkZU2iFc5deC3WhMm9FGzeYgHP5GD3tsFe16Y968DNcIeNNYChIMF9Ke6CpK6lTkIIY54iZzDG/s/NPgYqlVi3jXickxj/uOULhmMGZf3AkkHaIqWSsgjjK46pI50WZXzIK4Ir0=
  - secure: XxMNWJMPdg8XHrvVgNk1HiDCOLz+hpnh25XmV/c+n+qvqdXuJNNmR6Mw7yE+wf6/7pNiYhvpy0bkO+OHw+ZQtnI9v0MzUI3Hh38GvE4+Vu1vawehhWUyadnjZKd6oQgKN9lMZvV6sd4EmDCdJ1A+oYRE7jlsjLCbjhKQgP2nch0=
