#!/bin/bash

# Set up the data structure needed for the tests

set -e
set -u
set -x

OMERO_DIST=${OMERO_DIST:-/opt/omero/server/OMERO.server}
WORKDIR=$(mktemp -d)

function cleanup {
  rm -rf "$WORKDIR"
  echo "Deleted temp working directory $WORKDIR"
}

trap cleanup EXIT

export PATH=$PATH:${OMERO_DIST}/bin
omero login root@localhost -w omero
DATASET=$(omero obj new Dataset name=TestDataset)
PROJECT=$(omero obj new Project name=TestProject)
omero obj new ProjectDatasetLink parent=$PROJECT child=$DATASET
FILENAME="$WORKDIR/test&rectangle=10&ellipsis=10&points=10.fake"
touch "$FILENAME"
IMAGE=$(omero import --output=ids  "$FILENAME" -T Dataset:id:1)

OPEN=$(omero obj new TagAnnotation textValue=open description=boundaryType)
CLOSED=$(omero obj new TagAnnotation textValue=closed description=boundaryType)

# TBD
# for x in $(seq 0 9);
# do
#     omero obj new ShapeAnnotationLink parent=Rectangle: child=$OPEN
# done
