#!/bin/bash

# Set up the data structure needed for the tests

set -e
set -u
set -x

OMERO_DIST=${OMERO_DIST:-/opt/omero/server/OMERO.server}
WORKDIR=$(mktemp -d)

function cleanup {
  rm -rf "$WORKDIR"
  echo "Deleted temp working directory $WORKDIR"
}

trap cleanup EXIT

export PATH=$PATH:${OMERO_DIST}/bin
omero login root@localhost -w omero
DATASET=$(omero obj new Dataset name=TestDataset)
PROJECT=$(omero obj new Project name=TestProject)
omero obj new ProjectDatasetLink parent=$PROJECT child=$DATASET

FILENAME="$WORKDIR/test&ellipses=10&points=10&rectangles=10.fake"
touch "$FILENAME"
IMAGE=$(omero import --output=ids "$FILENAME" -T $DATASET)

OPEN=$(omero obj new TagAnnotation textValue=open description=boundaryType)
CLOSED=$(omero obj new TagAnnotation textValue=closed description=boundaryType)
QUERY="select s from Dataset d join d.imageLinks dil join dil.child as i join i.rois as r join r.shapes as s where d.id = ${DATASET##Dataset:}"
for shape in $(omero -q hql --limit=100 --style=csv "$QUERY" | grep -v Class);
do
    class=$(echo $shape | awk -F, '{print $2}' | tr -d I)
    oid=$(echo $shape | awk -F, '{print $3}')
    omero obj new ShapeAnnotationLink parent=$class:$oid child=$OPEN
done

export OMERO_PREFIX=/opt/omero/server/OMERO.server
export PYTHONPATH=$OMERO_PREFIX/lib/python

python /imagej-omero/.omeroci/create-table.py
